export const database = [
    {id: 1, firstname: 'Cédric', lastname: 'Ménard', state: ''},
    {id: 2, firstname: 'Clotilde', lastname: 'Bachelet', state: ''},
    {id: 3, firstname: 'Rémi', lastname: 'Couturier', state: ''},
    {id: 4, firstname: 'Yseult', lastname: 'Duclos', state: ''},
    {id: 5, firstname: 'Jérémie', lastname: 'Kléber', state: ''},
    {id: 6, firstname: 'Marthe', lastname: 'Auch', state: ''},
    {id: 7, firstname: 'Albert', lastname: 'Gribelin', state: ''},
    {id: 8, firstname: 'Marie-Françoise', lastname: 'Allais', state: ''},
    {id: 9, firstname: 'Timothée', lastname: 'Allard', state: ''},
    {id: 10, firstname: 'Bérangère', lastname: 'Tourneur', state: ''},
    {id: 11, firstname: 'Nathanaël', lastname: 'Boulet', state: ''},
    {id: 12, firstname: 'Justine', lastname: 'Levett', state: ''},
    {id: 13, firstname: 'Auguste', lastname: 'Renou', state: ''},
    {id: 14, firstname: 'Jeanne', lastname: 'Pierlot', state: ''},
    {id: 15, firstname: 'Théo', lastname: 'Pleimelding', state: ''},
    {id: 16, firstname: 'Geneviève', lastname: 'Genet', state: ''},
    {id: 17, firstname: 'Edgar', lastname: 'Bonnel', state: ''},
    {id: 18, firstname: 'Liliane', lastname: 'Fétique', state: ''},
    {id: 19, firstname: 'Antoine', lastname: 'Abadie', state: ''},
    {id: 20, firstname: 'Irène', lastname: 'Silvestre', state: ''},
]